version: 2

build:
  image: latest

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: true

python:
    install:
    -   method: pip
        path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
        # extra_requirements: 
        # -   docs
        # - requirements.txt

# Use conda instead of python
conda:
  environment: docs/environment.yml