version: 2

build:
  image: latest

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: true

python:
    install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    # install:
    # -   method: pip
    #     path: .
    #     extra_requirements: 
    #     -   docs
    #     - requirements.txt