version: 2

build:
  image: latest

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    version: 3.7
    install:
    - requirements: docs/requirements.txt
    # install:
    # -   method: pip
    #     path: .
    #     extra_requirements:
    #     -   docs