[tool.poetry]
name = "scReadSim"
version = "0.1.0"
description = ""
authors = ["Guan'ao Yan"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
